#!/bin/bash
regexp="$HOME/Backup-[0-9]{4}-[0-9]{2}-[0-9]{2}$"
backup=-1
backup_folder=-1
restore="$HOME/restore"
[[ -d "$restore" ]] && rm -r "$restore"
mkdir "$restore"
for file in ~/*
do
	if [[ $file =~ $regexp ]]
	then
		year="$(echo ${file##*/} | cut -d '-' -f 2)"
		month="$(echo ${file##*/} | cut -d '-' -f 3)"
		day="$(echo ${file##*/} | cut -d '-' -f 4)"
		date="$(date -d "$year-$month-$day" +%s)"
		if [ $backup -lt $date ]
		then
			backup=$date
			backup_folder=$file
		fi
	fi
done
regexp=".+-[0-9]{4}-[0-9]{2}-[0-9]{2}$"
if [ $backup -eq -1 ]
then
	echo "you haven't created backups yet"
	exit 0
else
	
	for file in $(find $backup_folder)
	do	
		if [[ ! $file =~ $regexp ]]
		then
			# echo $file
			name=${file#$backup_folder}
			# echo $name $file
			if [[ -f $file ]] 
			then
				cp $file "$restore$name"
			else
				[[ -d "$restore$name" ]] || mkdir "$restore$name"
			fi
		fi
	done
	for file in $(find $backup_folder)
	do	
		if [[ $file =~ $regexp ]]
		then
			name=${file#$backup_folder}
			nameWithoutDate="$(echo $name | cut -d '-' -f 1)"
			# echo $name $file
			if [[ -f $restore$nameWithoutDate ]] 
			then
				continue
			elif [[ -f $file ]]
			then
				cp $file "$restore$name"
			fi
		fi
	done
fi
	
